### ISSUE TITLE
Error when getting model because of Transformers version 

### ISSUE THREAD

**Issue by bytecell** [SKTBrain/KoBERT#31]
* 현상
   - 아래와 같이 README.md 의 install 방법에 따라 설치한 후, 아래 코드를 수행할 경우 에러 발생

```python
import torch
from kobert.pytorch_kobert import get_pytorch_kobert_model
model, vocab  = get_pytorch_kobert_model()

Traceback (most recent call last):
  File "pp.py", line 3, in <module>
    model, vocab  = get_pytorch_kobert_model()
  File "/home/jjlee/KoBERT/kobert/pytorch_kobert.py", line 64, in get_pytorch_kobert_model
    return get_kobert_model(model_path, vocab_path, ctx)
  File "/home/jjlee/KoBERT/kobert/pytorch_kobert.py", line 69, in get_kobert_model
    bertmodel.load_state_dict(torch.load(model_file))
  File "/home/jjlee/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BertModel:
        Missing key(s) in state_dict: "embeddings.position_ids".
```

* 원인
   - requirements.txt 에 따라 설치하면 각 패키지의 최신 버전이 설치되는데, transformers 패키지의 버전 차이로 인한 문제로 보여짐

**Comment by bytecell** [comment]
* 분석
   - 예상되는 원인을 바탕으로, 설치된 transformers 를 remove 한 후, transformers==2.1.1 로 설치

```
pip3 uninstall transformers
pip3 install transformers==2.1.1
```

**Comment by bytecell** [comment]
<h4>해결방안</h4>

* transformers 버전을 requirements 에서 명시
    - 이를 위해, transformers 버전 범위를 확인 필요

**Comment by bytecell** [comment]
@haven-jeon 
이와 관련하여,
README.md 파일과 requirements.txt 를 수정하는 branch 를 업로드해도 될지 문의합니다.
push 권한 제한이 있는 것 같아서요.

**Comment by haven-jeon** [comment]
네 감사합니다. PR 주시면 될거 같습니다. ^^

**Comment by haven-jeon** [comment]
#37 

버전 호환 가능하니 확인 부탁드립니다. ^^

**Comment by bytecell** [comment]
네, 확인하였습니다. BertConfig 의존성을 없앴군요. 감사합니다.
